
// Build with COMPILE test /C

#include "oohg.ch"

REQUEST HB_CODEPAGE_BG866
REQUEST HB_CODEPAGE_BGISO
REQUEST HB_CODEPAGE_BGMIK
REQUEST HB_CODEPAGE_BGWIN
REQUEST HB_CODEPAGE_CS852
REQUEST HB_CODEPAGE_CS852C
REQUEST HB_CODEPAGE_CSISO
REQUEST HB_CODEPAGE_CSKAMC
REQUEST HB_CODEPAGE_CSWIN
REQUEST HB_CODEPAGE_DE850
REQUEST HB_CODEPAGE_DE850M
REQUEST HB_CODEPAGE_DEISO
REQUEST HB_CODEPAGE_DEWIN
REQUEST HB_CODEPAGE_DK865
REQUEST HB_CODEPAGE_EL437
REQUEST HB_CODEPAGE_EL737
REQUEST HB_CODEPAGE_ELISO
REQUEST HB_CODEPAGE_ELWIN
REQUEST HB_CODEPAGE_EN
REQUEST HB_CODEPAGE_ES850
REQUEST HB_CODEPAGE_ES850C
REQUEST HB_CODEPAGE_ES850M
REQUEST HB_CODEPAGE_ESISO
REQUEST HB_CODEPAGE_ESMWIN
REQUEST HB_CODEPAGE_ESWIN
REQUEST HB_CODEPAGE_FI850
REQUEST HB_CODEPAGE_FR850
REQUEST HB_CODEPAGE_FR850M
REQUEST HB_CODEPAGE_FRISO
REQUEST HB_CODEPAGE_FRWIN
REQUEST HB_CODEPAGE_HR646
REQUEST HB_CODEPAGE_HR852
REQUEST HB_CODEPAGE_HRISO
REQUEST HB_CODEPAGE_HRWIN
REQUEST HB_CODEPAGE_HU852
REQUEST HB_CODEPAGE_HU852C
REQUEST HB_CODEPAGE_HUISO
REQUEST HB_CODEPAGE_HUWIN
REQUEST HB_CODEPAGE_IS850
REQUEST HB_CODEPAGE_IS861
REQUEST HB_CODEPAGE_IT437
REQUEST HB_CODEPAGE_IT850
REQUEST HB_CODEPAGE_IT850M
REQUEST HB_CODEPAGE_ITISB
REQUEST HB_CODEPAGE_ITISO
REQUEST HB_CODEPAGE_ITWIN
REQUEST HB_CODEPAGE_LT775
REQUEST HB_CODEPAGE_LTWIN
REQUEST HB_CODEPAGE_NL850
REQUEST HB_CODEPAGE_NL850M
REQUEST HB_CODEPAGE_NO865
REQUEST HB_CODEPAGE_PL852
REQUEST HB_CODEPAGE_PLISO
REQUEST HB_CODEPAGE_PLMAZ
REQUEST HB_CODEPAGE_PLWIN
REQUEST HB_CODEPAGE_PT850
REQUEST HB_CODEPAGE_PT860
REQUEST HB_CODEPAGE_PTISO
REQUEST HB_CODEPAGE_RO852
REQUEST HB_CODEPAGE_ROISO
REQUEST HB_CODEPAGE_ROWIN
REQUEST HB_CODEPAGE_RU1251
REQUEST HB_CODEPAGE_RU866
REQUEST HB_CODEPAGE_RUKOI8
REQUEST HB_CODEPAGE_SK852
REQUEST HB_CODEPAGE_SKISO
REQUEST HB_CODEPAGE_SKKAMC
REQUEST HB_CODEPAGE_SKWIN
REQUEST HB_CODEPAGE_SL646
REQUEST HB_CODEPAGE_SL852
REQUEST HB_CODEPAGE_SLISO
REQUEST HB_CODEPAGE_SLWIN
REQUEST HB_CODEPAGE_SRWIN
REQUEST HB_CODEPAGE_SV437C
REQUEST HB_CODEPAGE_SV850
REQUEST HB_CODEPAGE_SV850M
REQUEST HB_CODEPAGE_SVISO
REQUEST HB_CODEPAGE_SVWIN
REQUEST HB_CODEPAGE_TR857
REQUEST HB_CODEPAGE_TRISO
REQUEST HB_CODEPAGE_TRWIN
REQUEST HB_CODEPAGE_UA1125
REQUEST HB_CODEPAGE_UA1251
REQUEST HB_CODEPAGE_UA866
REQUEST HB_CODEPAGE_UAKOI8
REQUEST HB_CODEPAGE_UTF8

REQUEST HB_GT_WIN_DEFAULT

PROCEDURE Main

   as := { "BG866",  "BGISO",  "BGMIK",  "BGWIN", "CS852",  "CS852C", "CSISO",  "CSKAMC", "CSWIN",  "DE850",  "DE850M", ;
           "DEISO",  "DEWIN",  "DK865",  "EL437", "EL737",  "ELISO",  "ELWIN",  "EN",     "ES850",  "ES850C", "ES850M", ;
           "ESISO",  "ESMWIN", "ESWIN",  "FI850", "FR850",  "FR850M", "FRISO",  "FRWIN",  "HR646",  "HR852",  "HRISO",  ;
           "HRWIN",  "HU852",  "HU852C", "HUISO", "HUWIN",  "IS850",  "IS861",  "IT437",  "IT850",  "IT850M", "ITISB", ;
           "ITISO",  "ITWIN",  "LT775",  "LTWIN", "NL850",  "NL850M", "NO865",  "PL852",  "PLISO",  "PLMAZ",  "PLWIN",  ;
           "PT850",  "PT860",  "PTISO",  "RO852", "ROISO",  "ROWIN",  "RU1251", "RU866",  "RUKOI8", "SK852",  "SKISO",  ;
           "SKKAMC", "SKWIN",  "SL646",  "SL852", "SLISO",  "SLWIN",  "SRWIN",  "SV437C", "SV850",  "SV850M", "SVISO", ;
           "SVWIN",  "TR857",  "TRISO",  "TRWIN", "UA1125", "UA1251", "UA866",  "UAKOI8", "UTF8" }

   SETMODE( 25, 80 )
   CLS

   at := "·ÈÌÛ˙Ò—¸”‡ËÏÚ˘" + chr(147) + chr(128)
   k  := 0

   FOR j := 1 TO LEN( as )

     hb_cdpSelect( as[ j ] )
     ? at, " ", as[ j ]
     k++
     IF (k % 3) = 0
        WAIT
     ENDIF
   NEXT

RETURN
