name: OOHG Harbour 3.4 mingw 7.3 32/64 bits

on:
  push:
#  schedule:
#   - cron: "50 5 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'Harbour 3.4 mingw 7.3'
        default: 'oohg_hb34_0703'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: Harbour 3.4
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: oohg_hb34_0703.yml
         workflow_conclusion: success
         name: oohg_hb34_0703
         path: c:\temp
         repo: JoseQuintas/oohg

    - name: mingw
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb34_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/harbour_34

    - name: Unzip
      run: |
         c:
         dir c:\temp
         md c:\temp\harbour
         7z x -y c:\temp\oohg_hb34_0703.7z -oc:\temp\harbour
         7z x -y c:\temp\mingw_0703.7z -oc:\temp\mingw

    - name: Install Source Code
      env:
         REPO: ${{ github.repository }}
      run: |
         c:
         git clone https://github.com/$env:repo c:\temp\harbour\addons\oohg\samples --depth 1

    - name: Build 32 bits
      env:
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw64\bin
      run: |
         c:
         cd \temp\harbour\addons\oohg\samples
         hbmk2 -workdir=c:\temp testall.hbp

#    - name: Build 64 bits
#      env:
#         HB_COMPILER: mingw64
#         HB_INSTALL_PREFIX: c:\temp\harbour
#         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw64\bin
#      run: |
#         c:
#         cd \temp\harbour\addons\oohg\samples
#         hbmk2 -workdir=c:\temp testall.hbp

    - name: Save hb/oohg
      uses: actions/upload-artifact@v2
      with:
         name: oohg_hb34_0703
         path: c:\temp\oohg_hb34_0703.7z

#    - name: Save mingw
#      uses: actions/upload-artifact@v2
#      with:
#         name: mingw_0703
#         path: c:\temp\mingw_0703.7z
