@ECHO OFF
if "%HG_ROOT%"="" set HG_ROOT=c:\oohg
SET "TPATH=%PATH%"
SET "PATH=%HG_ROOT%"
SET HG_ADDLIBS_TEMP=%HG_ADDLIBS%
SET HG_ADDLIBS=%HG_ADDLIBS% -lrddado -lhbusrrdd
CALL COMPILE ADO
SET HG_ADDLIBS=%HG_ADDLIBS_TEMP%
SET "PATH=%TPATH%"
SET TPATH=
